###############################################
# 環境変数                                    #
###############################################
export PATH=/usr/local/bin:$PATH$
export EDITOR=/usr/bin/vim

# 言語の設定
LANG=ja_JP.UTF-8
export LANG

# 補完リストが多いときに尋ねる数
# -1 : 尋ねない
#  0 : ウィンドウから溢れるときは尋ねる
LISTMAX=0
export LISTMAX

# rbenv
eval "$(rbenv init -)"
