# users generic .zshrc file for zsh(1)

# ------------------------------
# General Settings
# ------------------------------
export LANG=ja_JP.UTF-8  # 文字コードをUTF-8に設定
export KCODE=u           # KCODEにUTF-8を設定
export AUTOFEATURE=true  # autotestでfeatureを動かす
export EDITOR=vim        # エディタをvimに設定
export PAGER=less        # ベージャをlessに設定

case ${OSTYPE} in
  darwin*)
    # MacではMacVimを起動する
    export EDITOR=/Applications/MacVim.app/Contents/MacOS/Vim
    alias vi='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim "$@"'
    alias vim='env LANG=ja_JP.UTF-8 /Applications/MacVim.app/Contents/MacOS/Vim "$@"'
    ;;
  linux*)
    alias vi='vim'
    ;;
esac

#bindkey -e               # キーバインドをemacsモードに設定
bindkey -v               # キーバインドをviモードに設定

setopt no_beep           # ビープ音を鳴らさないようにする
setopt auto_cd           # 指定したコマンド名がなく、ディレクトリ名と一致した場合 cd する
setopt auto_pushd        # cd時にディレクトリスタックにpushdする
setopt correct           # コマンドのスペルを訂正する
setopt prompt_subst      # プロンプト定義内で変数置換やコマンド置換を扱う
setopt notify            # バックグラウンドジョブの状態変化を即時報告する
setopt equals            # =commandを`which command`と同じ処理にする
#setopt chase_links x     # シンボリックリンクは実体を追うようになる
#setopt NO_hup            # シェルが終了しても裏ジョブに HUP シグナルを送らないようにする
#setopt ignore_eof        # Ctrl+D では終了しないようになる（exit, logout などを使う）
#setopt print_exit_value  # 戻り値が 0 以外の場合終了コードを表示する
#setopt rm_star_silent    # rm * などの際、本当に全てのファイルを消して良いかの確認しないようになる
#setopt rm_star_wait      # rm_star_silent の逆で、10 秒間反応しなくなり、頭を冷ます時間が与えられる

### Complement ###
setopt nolistbeep              # 補完候補表示時などにビープ音を鳴らさない
setopt print_eight_bit         # 日本語補完時の文字化け防止
setopt auto_list               # 補完候補が複数ある時に、一覧表示する
setopt magic_equal_subst       # =以降も補完する(--prefix=/usrなど)
setopt auto_param_slash        # ディレクトリ名の補完で末尾の / を自動的に付加
setopt auto_param_keys         # カッコの対応などを自動的に補完する
setopt auto_menu               # 補完キー（Tab, Ctrl+I) を連打するだけで順に補完候補を自動で補完する
setopt list_packed             # 補完候補をできるだけ詰めて表示する
setopt list_types              # 補完候補にファイルの種類も表示する
setopt always_to_end           # 補完したら文字列末尾へ移動
setopt complete_aliases        # aliasも補完対象にする
bindkey "^[[Z" reverse-menu-complete  # Shift-Tabで補完候補を逆順する("\e[Z"でも動作する)
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' # 補完時に大文字小文字を区別しない

### Glob ###
setopt extended_glob # グロブ機能を拡張する
unsetopt caseglob    # ファイルグロブで大文字小文字を区別しない

### History ###
HISTFILE=~/.zsh_history   # ヒストリを保存するファイル
HISTSIZE=10000            # メモリに保存されるヒストリの件数
SAVEHIST=10000            # 保存されるヒストリの件数
setopt bang_hist          # !を使ったヒストリ展開を行う(d)
setopt extended_history   # ヒストリに実行時間も保存する
setopt hist_ignore_dups   # 直前と同じコマンドはヒストリに追加しない
setopt share_history      # 他のシェルのヒストリをリアルタイムで共有する
setopt hist_reduce_blanks # 余分なスペースを削除してヒストリに保存する
setopt hist_no_store      # history (fc -l) コマンドをヒストリリストから取り除く。
setopt hist_verify        # ヒストリを呼び出してから実行する間に一旦編集できる状態になる

# マッチしたコマンドのヒストリを表示できるようにする
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

# すべてのヒストリを表示する
function history-all { history -E 1 }

# ------------------------------
# Look And Feel Settings
# ------------------------------

### Prompt ###
autoload colors; colors

function rprompt-git-current-branch {
  local name st color

  if [[ "$PWD" =~ '/\.git(/.*)?$' ]]; then
    return
  fi
  name=$(basename "`git symbolic-ref HEAD 2> /dev/null`")
  if [[ -z $name ]]; then
    return
  fi
  st=`git status 2> /dev/null`
  if [[ -n `echo "$st" | grep "^nothing to"` ]]; then
    color=${fg[green]}
  elif [[ -n `echo "$st" | grep "^nothing added"` ]]; then
    color=${fg[yellow]}
  elif [[ -n `echo "$st" | grep "^# Untracked"` ]]; then
    color=${fg_bold[red]}
  else
    color=${fg[red]}
  fi

  # %{...%} は囲まれた文字列がエスケープシーケンスであることを明示する
  # これをしないと右プロンプトの位置がずれる
  echo "%{$color%}$name%{$reset_color%} "
}

# 一般ユーザ時
tmp_prompt="%{${fg[cyan]}%}%# %{${reset_color}%}"
tmp_prompt2="%{${fg[cyan]}%}%_> %{${reset_color}%}"
tmp_rprompt='[`rprompt-git-current-branch`%~]'
# tmp_rprompt='[`rprompt-git-current-branch`%32<...<%~]'   # 文字数省略版
tmp_sprompt="%{${fg[yellow]}%}%r is correct? [Yes, No, Abort, Edit]:%{${reset_color}%}"

# rootユーザ時(太字にし、アンダーバーをつける)
if [ ${UID} -eq 0 ]; then
  tmp_prompt="%B%U${tmp_prompt}%u%b"
  tmp_prompt2="%B%U${tmp_prompt2}%u%b"
  tmp_rprompt="%B%U${tmp_rprompt}%u%b"
  tmp_sprompt="%B%U${tmp_sprompt}%u%b"
fi

PROMPT=$tmp_prompt    # 通常のプロンプト
PROMPT2=$tmp_prompt2  # セカンダリのプロンプト(コマンドが2行以上の時に表示される)
RPROMPT=$tmp_rprompt  # 右側のプロンプト
SPROMPT=$tmp_sprompt  # スペル訂正用プロンプト
# SSHログイン時のプロンプト
[ -n "${REMOTEHOST}${SSH_CONNECTION}" ] &&
  PROMPT="%{${fg[white]}%}${HOST%%.*} ${PROMPT}"
;

# set terminal title including current directory
case "${TERM}" in
kterm*|xterm*)
  precmd() {
    #echo -ne "\033]0;${USER}@${HOST%%.*}:${PWD}\007"
    echo -ne ""
  }
  export LSCOLORS=exfxcxdxbxegedabagacad
  export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
  zstyle ':completion:*' list-colors \
    'di=34' 'ln=35' 'so=32' 'ex=31' 'bd=46;34' 'cd=43;34'
  ;;
esac


# ## PROMPT
# PROMPT=$'[%*] → '
# ## RPROMPT
# RPROMPT=$'`branch-status-check` %~' # %~はpwd
# setopt prompt_subst #表示毎にPROMPTで設定されている文字列を評価する
#  
# # {{{ methods for RPROMPT
# # fg[color]表記と$reset_colorを使いたい
# # @see https://wiki.archlinux.org/index.php/zsh
# autoload -U colors; colors
# function branch-status-check {
#     local prefix branchname suffix
#         # .gitの中だから除外
#         if [[ "$PWD" =~ '/\.git(/.*)?$' ]]; then
#             return
#         fi
#         branchname=`get-branch-name`
#         # ブランチ名が無いので除外
#         if [[ -z $branchname ]]; then
#             return
#         fi
#         prefix=`get-branch-status` #色だけ返ってくる
#         suffix='%{'${reset_color}'%}'
#         echo ${prefix}${branchname}${suffix}
# }
# function get-branch-name {
#     # gitディレクトリじゃない場合のエラーは捨てます
#     echo `git rev-parse --abbrev-ref HEAD 2> /dev/null`
# }
# function get-branch-status {
#     local res color
#         output=`git status --short 2> /dev/null`
#         if [ -z "$output" ]; then
#             res=':' # status Clean
#             color='%{'${fg[green]}'%}'
#         elif [[ $output =~ "[\n]?\?\? " ]]; then
#             res='?:' # Untracked
#             color='%{'${fg[yellow]}'%}'
#         elif [[ $output =~ "[\n]? M " ]]; then
#             res='M:' # Modified
#             color='%{'${fg[red]}'%}'
#         else
#             res='A:' # Added to commit
#             color='%{'${fg[cyan]}'%}'
#         fi
#         # echo ${color}${res}'%{'${reset_color}'%}'
#         echo ${color} # 色だけ返す
# }

## terminal configuration
unset LSCOLORS
case "${TERM}" in
xterm)
  export TERM=xterm-color
  ;;
kterm)
  export TERM=kterm-color
  # set BackSpace control character
  stty erase
  ;;
cons25)
  unset LANG
  export LSCOLORS=ExFxCxdxBxegedabagacad
  export LS_COLORS='di=01;34:ln=01;35:so=01;32:ex=01;31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
  zstyle ':completion:*' list-colors \
    'di=;34;1' 'ln=;35;1' 'so=;32;1' 'ex=31;1' 'bd=46;34' 'cd=43;34'
  ;;
esac

# ------------------------------
# Keybind Settings
# ------------------------------
bindkey -v
bindkey '^R' history-incremental-search-backward

# ------------------------------
# Other Settings
# ------------------------------

# cdコマンド実行後、lsを実行する
#function cd() {
#  builtin cd $@ && ls;
#}

### PATH ###
export PATH=$HOME/bin:/usr/local/bin:$PATH
export MANPATH=/opt/local/man:$MANPATH

### Aliases ###
alias c="clear"
alias r=rails
alias rm="rm -i"
alias mv="mv -i"
alias gits="git status"
alias pd=popd
alias screen="screen -D -RR"     # auto detach
alias tm=tmux

# ls
case "${OSTYPE}" in
freebsd*|darwin*)
  alias ls="ls -G -w"
  ;;
linux*)
  alias ls="ls -F --color"
  ;;
esac

### Rails spring ###
case ${OSTYPE} in
  linux*)
    # vagrantのvboxsfにsocketファイルを生成できない為
    export SPRING_TMP_PATH=/tmp
    ;;
esac

### iTerm2のタブ名を変更する ###
function title {
  echo -ne "\033]0;"$*"\007"
  export TITLE="${(pj: :)@}"
}

chpwd() {
  title $(basename "$(pwd)")
}

### color-diff ###
if [[ -x `which colordiff` ]]; then
  alias diff='colordiff -u'
else
  alias diff='diff -u'
fi

### zsh-completions ###
fpath=(/usr/local/share/zsh-completions $fpath)

# ------------------------------
# 環境依存設定ファイル読み込み
# ------------------------------

[ -f ~/.zshrc.local ] && source ~/.zshrc.local ]


# ------------------------------
# 補完機能を有効にする
# ------------------------------
autoload -U compinit; compinit -u

